language: node_js
node_js:
  - '0.10'
before_script:
  - npm install -g bower grunt-cli
  - bower install
after_success:
  - grunt gh-pages
env:
 global:
 - secure: "QrLeoCTCyJjEShymxcPeHO8sm1Jk+RPPBdgQjsIth0HE3cRXQRlPSEPzepRpgVIeL0kkuD/rMQDajdBTiG8ojJW2lFWWh9qxjeGnrY5maWHSh+NwRxf1+v4V8OHgqzR1WTQPck/P5/F8xOwgBcgG9wC6v6cDoe7pJSKpXUYRs70="
notifications:
  email: false
  webhooks:
    urls:
      secure: "XXt1deuQcS2B6WE+7M0EWU/KQMnFEvqjblUdtkb9fhbTJJ8h4tK8VbUPVAaQNT0OpXgzrguZXvUbofQ+84N5XiWQPEiALb0JB7v30apO3vm86znBZ973d7CcerFPBc8JUWKfvr/xMWLzsx/fNoIoi6rGgW/x+yvsFiUpKcEOkxg="
